name: CI/CD Pipeline with Kubernetes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Keep your existing build and test jobs...

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/my-js-app
          kubectl rollout status deployment/my-nginx
          kubectl rollout status deployment/my-mongodb

deploy:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  needs: [build, test]
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=./kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/
        kubectl rollout restart deployment/my-js-app deployment/nginx