---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home"  # Update this path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "B14ckc0d3r"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "B14ckc0d3rSaeed"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: my-namespace
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoface
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: mongoface
  replicas: 1
  template:
    metadata:
      labels:
        app: mongoface
    spec:
      containers:
        - name: mongoface
          image: samueltallet/mongodb-php-gui
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mongoface
  namespace: my-namespace
spec:
  ports:
    - port: 5000
  selector:
    app: mongoface

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongoface-ingress
  namespace: my-namespace
  annotations:
    nginx.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: "nginx"
  rules:
    - host: mongoface.example.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongoface
                port:
                  number: 5000
