name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0' # specify the kubectl version

      - name: Configure kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Copy Kubernetes manifests to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no -r k8s/* root@$SERVER_IP:/home/k8s/
          rm ssh_key

      - name: Deploy to K3s
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            kubectl create namespace myapp --dry-run=client -o yaml | kubectl apply -f -

            kubectl create secret docker-registry dockerhub-secret \
              --docker-server=https://index.docker.io/v1/ \
              --docker-username=$DOCKER_USERNAME \
              --docker-password=$DOCKER_PASSWORD \
              --namespace=myapp \
              --dry-run=client -o yaml | kubectl apply -f -

            kubectl create secret docker-registry github-secret \
              --docker-server=https://ghcr.io \
              --docker-username=$GITHUB_USERNAME \
              --docker-password=$GITHUB_TOKEN \
              --namespace=myapp \
              --dry-run=client -o yaml | kubectl apply -f -

            kubectl apply -f /home/k8s/ -n myapp

            kubectl rollout status deployment/mongodb -n myapp
            kubectl rollout status deployment/app -n myapp
            kubectl rollout status deployment/app-test -n myapp
            kubectl rollout status deployment/nginx -n myapp
            kubectl rollout status deployment/mongoface -n myapp
          "
          rm ssh_key

      - name: Verify deployment
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            kubectl get pods -n myapp
            kubectl get services -n myapp
          "
          rm ssh_key
