name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  #  needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Kubernetes manifests to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no -r appkube/* root@$SERVER_IP:/home/app/
          rm ssh_key

      - name: Deploy to K3s
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            kubectl create namespace myapp --dry-run=client -o yaml | kubectl apply -f -

            # Create DockerHub registry secret
            kubectl create secret docker-registry dockerhub-registry-secret \
              --docker-server=https://index.docker.io/v1/ \
              --docker-username=$DOCKER_USERNAME \
              --docker-password=$DOCKER_PASSWORD \
              --namespace=myapp \
              --dry-run=client -o yaml | kubectl apply -f -

            # Create GitHub Container registry secret
            kubectl create secret docker-registry github-registry-secret \
              --docker-server=https://ghcr.io \
              --docker-username=$GITHUB_USERNAME \
              --docker-password=$GITHUB_TOKEN \
              --namespace=myapp \
              --dry-run=client -o yaml | kubectl apply -f -

            kubectl apply -f /home/app/ -n myapp

            kubectl rollout status deployment/mongodb -n myapp
            kubectl rollout status deployment/my-js-app -n myapp
            kubectl rollout status deployment/my-js-app-test -n myapp
            kubectl rollout status deployment/nginx -n myapp
            kubectl rollout status deployment/mongoface -n myapp
          "
          rm ssh_key

      - name: Verify deployment
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no root@$SERVER_IP "
            kubectl get pods -n myapp
            kubectl get services -n myapp
          "
          rm ssh_key
