apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
      - name: mongodb
        image: ghcr.io/0xcryp70/my-mongodb:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.40
        ports:
        - containerPort: 9216
        env:
        - name: MONGODB_URI
          value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb:27017"
      volumes:
      - name: mongodb-data
        hostPath:
          path: /mongodb-data
          type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216

---
# File: k8s/mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# File: k8s/mongodb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# File: k8s/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  username: B14ckc0d3r
  password: B14ckc0d3rSaeed
